### ISSUE TITLE
Out-of-date dependencies

### ISSUE THREAD

**Issue by RyanGlScott** [nikita-volkov/criterion-plus#2]
`criterion-plus` has too restrictive upper bounds on many of its dependencies, including (but possibly not limited to):
- `criterion`
- `optparse-applicative`
- `string-conversions`
- `vector`

This prevents many packages, whose benchmarks depend on `criterion-plus`, from being listed on Stackage, such as `cases` and `ttrie`.

See also https://github.com/iu-parfunc/sc-haskell/issues/7

**Comment by nikita-volkov** [comment]
I know. However updating to the latest version of criterion won't quite be just about updating the dependency boundaries. It'll take time, which I simply don't have for this project right now. I'll gladly accept a PR though.

Concerning Stackage, fixing the benchmark deps is not required to list the packages there. E.g., the "cases" package, which you've mentioned is listed. All that's needed is to disable the benchmarks in the Stackage listing configuration.
